### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 67aa374 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 67aa374 with merge 67aa374...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f100xx/builds/234892274?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 67aa3741c3533a964bbff6059aad58da94bdddc5 to master...

**Pull request merged**
